### ISSUE TITLE
ES6 destructuring on import throws an error

### ISSUE THREAD

**Issue by bryanforbes** [palantir/tslint#399]
In the project I'm working on, we're using ES6 imports. tslint 2.2.0-beta is throwing an error attempting to parse it. For instance:

```ts
import { foo } from 'bar';
```

Produces the following backtrace:

```
/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/build/rules/noUnusedVariableRule.js:52
                this.validateReferencesForVariable(name.text, name.getStart())
                                                       ^
TypeError: Cannot read property 'text' of undefined
    at NoUnusedVariablesWalker.visitImportDeclaration (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/build/rules/noUnusedVariableRule.js:52:56)
    at NoUnusedVariablesWalker.SyntaxWalker.visitNode (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:41611:26)
    at /Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:41707:67
    at visitEachNode (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:5928:30)
    at Object.forEachChild (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:6070:24)
    at NoUnusedVariablesWalker.SyntaxWalker.walkChildren (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:41707:16)
    at NoUnusedVariablesWalker.SyntaxWalker.visitSourceFile (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:41495:18)
    at NoUnusedVariablesWalker.SyntaxWalker.visitNode (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:41671:26)
    at NoUnusedVariablesWalker.SyntaxWalker.walk (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:41348:18)
    at Rule.AbstractRule.applyWithWalker (/Users/bryan/Projects/dojo/dojo2/dojo-core/node_modules/tslint/bin/tslint-cli.js:42358:24)
```

This effectively makes the latest version of tslint useless for projects using the new ES6 module syntax.

**Comment by wbuchwalter** [comment]
+1, This bug is present at least in:
- noUnusedVariableRule
- noUseBeforeDeclareRule
- whitespaceRule

**Comment by iwuvjhdva** [comment]
+1

**Comment by Dynom** [comment]
+1

**Comment by Intellicode** [comment]
+1

**Comment by rasmusvhansen** [comment]
+1

**Comment by juergenzimmermann** [comment]
+1

**Comment by gustavgahm** [comment]
+1

**Comment by Dynom** [comment]
Any progress in this area? It's becoming a major inconvenience in our stack.

**Comment by wbuchwalter** [comment]
@Dynom you can see the progress here :  #411.
Also as a temporary fix you can delete the three rules mentioned above.

**Comment by adidahiya** [comment]
@Dynom yep, we're working on it!

#411, which should fix this problem for the `no-unused-variable` rule, has merged.
I just opened #420, which updates `no-use-before-declare` for the new module syntax.

**Comment by Dynom** [comment]
Thanks for the feedback guys, I've muted the situation by adding a few additional checks in the linter until it's properly fixed. I greatly appreciate all the hard work!

**Comment by leeavital** [comment]
It looks like we can close this. I just tried the example with the most up-to-date version and there are no problems.

**Comment by areologist** [comment]
@leeavital What version exactly? Just curious. I'm on tslint 2.2.0-beta + gulp-tslint ^3.0.1-beta + typescript ^1.5.0-beta and I'm still having this issue. Not aware of anything more up-to-date.

I can lint if I remove whitespace and no-use-before-declare rules.

**Comment by leeavital** [comment]
@areologist I'm should have mentioned I'm running from source.  This will be fixed in version 2.3.0.

**Comment by areologist** [comment]
Awsome. Thank you @leeavital.
